### PR TITLE
modify match-up page UI so the Vote button is more recognizable

### PR DESCRIPTION
**Pull request by saharj**
# Description

After talking to the stakeholders, we have decided to change the UI of the match-up page, so it is less confusing for the user that the Vote button is not for the last tile in the page. The location of the buttons, and relocation of the question button was decided by the stakeholders as well. 

I will attach a screenshot in a comment.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by saharj** [comment]
Here you can see the new location and new UI for the Vote, Back and question buttons.

Screen Shot 2021-01-21 at 4 27 27 PM

**Review by sjsussman — APPROVED** [review]
Nice updates!

**Comment by VictorDronov** [comment]
Nice, looks better and the buttons are more visible!

**Review by VictorDronov — COMMENTED** [review]
Looks Good!

**Review by VictorDronov — APPROVED** [review]

**Pull request merged**
