### PR TITLE
connected child dashboard to mission control

### PR DESCRIPTION
**Pull request by Schrese**
# Description
This is to hook up all of the routes so that all pages link up. The user should be able to log-in, get to a modal page, pick the account/user-type, enter a pin, and get to their respective dashboards.

Fixes #

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [x] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by Nick-Ohman — DISMISSED** [review]
Looks great!

**Review by SandraCoburn — DISMISSED** [review]
Great index clean up!

**Review by JLC6290 — DISMISSED** [review]

**Review by Nick-Ohman — CHANGES_REQUESTED** [review]
one small change

**Review by bramirez96 — APPROVED** [review]
Nice work! Can't wait to see it all running!!~~

**Review by Nick-Ohman — APPROVED** [review]
Thanks for the changes! Looks great!

**Pull request merged**
